server:
  port: 8080

spring:
  application:
    name: rabbitmq-consumer-app
  
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 5
        prefetch: 1
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 1.0

# Queue and Exchange Configuration
app:
  rabbitmq:
    queue:
      name: message.queue
      durable: true
    exchange:
      name: message.exchange
      type: direct
    routing-key: message.routing.key

# Logging
logging:
  level:
    com.example: DEBUG
    org.springframework.amqp: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,rabbitmq